---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-b
  labels:
    application: mongo-b
spec:
  replicas: 1
  selector:
    matchLabels:
      application: mongo-b
  template:
    metadata:
      labels:
        application: mongo-b
    spec:
      containers:
        - image: mirror.gcr.io/library/mongo:8.0
          name: mongo-b
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip"
            - "*"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
      volumes:
        - name: mongodb-data
          emptyDir: {}
---
